---
Name: cacheinclude
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\ORM\ManyManyList:
    class: 'Heyday\CacheInclude\SilverStripe\ManyManyList'
  SilverStripe\View\SSTemplateParser:
    properties:
      closedBlocks:
        cache: 'Heyday\CacheInclude\SilverStripe\TemplateParserBlockProvider::cacheTemplate'
      openBlocks:
        cache_include: 'Heyday\CacheInclude\SilverStripe\TemplateParserBlockProvider::cacheIncludeTemplate'
  CacheInclude:
    class: 'Heyday\CacheInclude\CacheInclude'
    constructor:
      0: '%$CacheIncludeConfig'
  CacheIncludeExpressionLanguage:
    class: 'Heyday\CacheInclude\ExpressionLanguage'
    constructor:
      0: '%$Symfony\Component\Cache\Adapter\FilesystemAdapter'
  CacheIncludeConfig:
    class: 'Heyday\CacheInclude\Configs\ArrayConfig'
  CacheIncludeViewableDataProcessor:
    class: 'Heyday\CacheInclude\Processors\ViewableDataProcessor'
  CacheIncludeKeyCreator:
    class: 'Heyday\CacheInclude\KeyCreators\ControllerBased'
  Heyday\CacheInclude\SilverStripe\BuildTask:
    class: 'Heyday\CacheInclude\SilverStripe\BuildTask'
    constructor:
      0: '%$CacheInclude'
  Heyday\CacheInclude\SilverStripe\InvalidationExtension:
    class: 'Heyday\CacheInclude\SilverStripe\InvalidationExtension'
    constructor:
      0: '%$CacheInclude'
      1: '%$CacheIncludeExpressionLanguage'
  RequestCacheMiddleware:
    class: 'Heyday\CacheInclude\SilverStripe\RequestCacheMiddleware'
    constructor:
      0: '%$CacheInclude'
      1: '%$CacheIncludeExpressionLanguage'
      2: 'Global'
    properties:
      Tokens:
        - '%$SilverStripe\Security\SecurityToken'
      SaveExcludeRules:
        - 'request.getUrl() matches "{^admin|dev}"'
      SaveIncludeRules:
        - "request.httpMethod() == 'GET'"
        - "response.getStatusCode() == 200"
      FetchExcludeRules:
        - 'request.getUrl() matches "{^admin|dev}"'
      FetchIncludeRules:
        - "request.httpMethod() == 'GET'"
---
Name: cacheinclude-cache
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.CacheInclude:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'CacheInclude'
---
Only:
  constantdefined: 'CACHEINCLUDE_FORCE_EXPIRE'
Except:
  environment: live
---
SilverStripe\Core\Injector\Injector:
  CacheInclude:
    class: 'Heyday\CacheInclude\CacheInclude'
    constructor:
      0: '%$CacheIncludeConfig'
      1: true
